/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.spraener.nxtgen.hello;

import de.spraener.nxtgen.hello.model.Person;

public class HelloWorld {
    public String getGreeting() {
        Person p = new Person();
        p.setName("Spräner");
        p.setFirstName("Carsten");
        return "Hello "+p.getFirstName()+" "+p.getName();
    }

    public static void main(String[] args) {
        System.out.println(new HelloWorld().getGreeting());
    }
}
