plugins {
    id 'java-library'
    id 'application'
}

def home = System.getenv("HOME")
def VP_HOME = "/Applications/Visual Paradigm.app/Contents/Resources/app";// System.getenv("VP_HOME")
def repoDir = "${project.rootDir}/../repo"
def version = '24.1.0'
def group = 'de.spraener.nxtgen'

targetCompatibility = JavaVersion.VERSION_11
sourceCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
    maven {
        url "file://$repoDir"
    }
    flatDir {
        dirs("${VP_HOME}/lib")
    }
}


sourceSets {
    main {
        java {
            srcDir('src/main/java-gen')
        }
    }
}

dependencies {

    implementation group: 'io.javalin', name: 'javalin', version: '5.0.0'
    implementation group: 'com.google.code.gson', name: 'gson', version: '2.8.5'
    implementation(":openapi:")
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    implementation group: 'org.apache.groovy', name: 'groovy', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-json', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-xml', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-templates', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-nio', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-sql', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-ant', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-datetime', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-dateutil', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-console', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-docgenerator', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-groovydoc', version: '4.0.15'
    implementation group: 'org.apache.groovy', name: 'groovy-swing', version: '4.0.15'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.1'
}

tasks.named('test') {
    useJUnitPlatform()
}

mainClassName = "de.spraener.nextgen.vpplugin.CgV19Plugin"
