// Refactoring the build especially the upload according to
// this article: https://central.sonatype.org/pages/gradle.html
plugins {
}

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    buildscript {
        apply plugin: 'maven-publish'
        apply plugin: 'java'

        repositories {
            mavenCentral()
        }
    }

    apply plugin: "maven-publish"

    publishing {
        publications {
            gpr(MavenPublication) {
                from(components.java)
            }
        }
        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/carstenSpraener/cgV19")
                credentials {
                    username = System.getenv("GITHUB_USERNAME")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}
