plugins {
    id 'java'
}

repositories {
    mavenCentral();
}

dependencies {
    implementation "de.spraener.nxtgen:cgv19-core:24.1.0"
    implementation "de.spraener.nxtgen:cgv19-oom:24.1.0"
    implementation "de.spraener.nxtgen:cgv19-aicb:24.1.0"

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.3'
    testImplementation 'org.assertj:assertj-core:3.24.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.3'
}

test {
    useJUnitPlatform()
}
