FROM node:lts-alpine as stage-env
ARG KDP_FRONTEND_CONFIG

WORKDIR /opt/{{projectName}}
RUN npm install -g @angular/cli;

FROM stage-env as stage-{{projectName}}
WORKDIR /opt/app

COPY ./package.json .
RUN  npm install

COPY . .
run ng build --base-href=/

FROM nginx:alpine3.17

WORKDIR /usr/share/nginx/html

COPY --from=stage-{{projectName}} /opt/app/dist/{{projectName}}/* /usr/share/nginx/html/

EXPOSE {{port}}
