buildscript {
    def version = '23.1.0'
    def group = 'de.spraener.nxtgen'

    repositories {
        mavenCentral();
        maven {
            url = "${project.rootDir}/../repo"
        }
        maven {
            url = "${project.rootDir}/../../repo"
        }
    }
    dependencies {
        classpath "${group}:cgv19-core:${version}"
        classpath "${group}:cgv19-gradle:${version}"
    }
}

plugins {
    id 'java-library'
}

apply plugin: 'de.spraener.nxtgen.cgV19'
apply plugin: "maven-publish"

repositories {
    mavenCentral();
    maven {
        url = "${project.rootDir}../../repo"
    }
}

cgV19 {
    //model = './src/main/helloWorld.oom'
    model = 'http://localhost:7001/de.spraener.nextgen.vpplugin.cartridge'
}

sourceSets {
    main {
        java {
            srcDir('src/main/java-gen')
        }
    }
}

dependencies {
    cartridge "de.spraener.nxtgen:cgv19-core:24.1.0"
    cartridge "de.spraener.nxtgen:cgv19-oom:24.1.0"
    cartridge "de.spraener.nxtgen:cgv19-metacartridge:24.1.0"

    implementation "de.spraener.nxtgen:cgv19-core:24.1.0"
    implementation "de.spraener.nxtgen:cgv19-oom:24.1.0"
    testImplementation 'junit:junit:4.13.1'
}
