server:
  port: 8008

spring:
  application:
    name: restDemo
  jpa:
    hibernate:
      ddl-auto: create
      database: h2
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:restdemo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  thymeleaf:
    cache: false

