buildscript {
    repositories {
        mavenCentral();
        maven {
            url="${project.rootDir}/../repo"
        }
    }
    dependencies {
        classpath "de.spraener.nxtgen:cgv19-core:25.0.0"
        classpath "de.spraener.nxtgen:cgv19-gradle:25.0.0"
    }
}

plugins {
    id 'java'
    id 'application'
}

apply plugin: 'de.spraener.nxtgen.cgV19'

repositories {
    mavenCentral();
    maven {
        url="${project.rootDir}/../repo"
    }
}

cgV19 {
    model = 'http://localhost:7001/de.spraener.nxtgen.ice'
}

sourceSets {
    main {
        java {
            srcDir('src/main/java-gen')
        }
    }
}

dependencies {
    cartridge "de.spraener.nxtgen:cgv19-core:25.0.0"
    cartridge "de.spraener.nxtgen:cgv19-oom:25.0.0"
    cartridge "de.spraener.nxtgen:cgv19-metacartridge:25.0.0"
    cartridge "de.spraener.nxtgen:cgv19-pojo:25.0.0"
    // Add additional cartridges here

    implementation "de.spraener.nxtgen:cgv19-core:25.0.0"
    implementation "de.spraener.nxtgen:cgv19-oom:25.0.0"
    implementation "de.spraener.nxtgen:cgv19-pojo:25.0.0"

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.3'
    testImplementation 'org.mockito:mockito-core:5.3.1'
    testImplementation 'org.mockito:mockito-junit-jupiter:4.6.1'
    testImplementation 'org.assertj:assertj-core:3.24.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.3'
}

test {
    useJUnitPlatform()
}

